
server:
  port: 9098

spring:
  jpa:
    generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud

eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
